version: '3'
services:
  selenium-hub:
    image: selenium/hub:3.141.59-20210929
    container_name: hub
    ports:
      - 4444:4444
    networks:
      - test-automation-setup
  chrome:
    image: selenium/node-chrome:3.141.59-20210929
    container_name: chrome
    networks:
      - test-automation-setup
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444
  firefox:
    image: selenium/node-firefox:3.141.59-20210929
    container_name: firefox
    networks:
    - test-automation-setup
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444
  mvn-tests: 
    image: mvn_test
    build: ./
    container_name: mvn_test
    networks:
    - test-automation-setup
networks:
  test-automation-setup:
    external: true